import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const leer = (ruta) => readFileSync(new URL(`../${ruta}`, import.meta.url), 'utf8')
const adminHtml = leer('admin.html')
const accessHtml = leer('access.html')
const admin = leer('src/pages/admin.js')
const access = leer('src/pages/access.js')
const estilos = leer('src/styles/global.css')
const estilosPortal = leer('src/styles/portal.css')
const funcionAdministrativa = leer('supabase/functions/admin-manage-user/index.ts')

describe('barrera visual del portal administrador', () => {
  it('mantiene oculto admin.html hasta completar sesión, rol y AAL2', () => {
    expect(adminHtml).toContain('class="ruta-protegida-pendiente"')
    expect(adminHtml).toContain('Validando acceso administrativo…')
    expect(estilos).toContain('html.ruta-protegida-pendiente body > :not(.estado-ruta-protegida)')
    expect(admin.indexOf("await protegerRuta('admin')"))
      .toBeLessThan(admin.indexOf("classList.remove('ruta-protegida-pendiente')"))
  })

  it('valida AAL2 desde el selector antes de navegar a admin.html', () => {
    expect(accessHtml).toContain('data-admin-access')
    expect(access).toContain('evento.preventDefault()')
    expect(access).toContain("await protegerRuta('admin')")
    expect(access.indexOf("await protegerRuta('admin')"))
      .toBeLessThan(access.indexOf('window.location.assign(enlaceAdmin.href)'))
  })

  it('usa un encabezado operativo y un estado de menú independiente', () => {
    expect(adminHtml).toContain('encabezado-global--admin')
    expect(adminHtml).toContain('data-menu-lateral-toggle')
    expect(adminHtml).toContain('data-alertas-operativas')
    expect(adminHtml).toContain('Pulso operativo')
    expect(adminHtml).toContain('<details class="detalle-admin">')
    expect(adminHtml).toContain('data-metrica="gmail_pendientes"')
    expect(adminHtml).not.toContain('marca--lateral')
    expect(admin).toContain("inicializarColapsoLateral({ clave: 'agenkin_menu_admin_colapsado'")
    expect(leer('src/pages/app.js')).toContain("inicializarColapsoLateral({ clave: 'agenkin_menu_lateral_colapsado' })")
    expect(admin).toContain('detener_carga_historica')
    expect(admin).toContain('alerta_mas_antigua_minutos')
    expect(admin).toContain('gmail_antiguedad_minutos')
    expect(admin).toContain('calendar_antiguedad_minutos')
    expect(admin).toContain('conexiones_token_vencido')
    expect(admin).not.toContain("from('notificaciones')")
    expect(estilosPortal).toContain('body.portal--admin.menu-admin-colapsado .menu-lateral-toggle')
    expect(funcionAdministrativa).toContain('if (metricasResultado.error)')
    expect(funcionAdministrativa).not.toContain('metricasResultado.error || notificacionesResultado.error')
    expect(estilosPortal).toContain('grid-template-columns: repeat(3, minmax(220px, 1fr))')
    expect(estilosPortal).toContain('.encabezado-global__tarjetas--admin .tarjeta-encabezado { min-width: 220px; flex: 0 0 220px; }')
    expect(estilosPortal).toContain('.panel-alertas-operativas[hidden] { display: none; }')
    expect(adminHtml).toContain('data-icon="switch_account"')
    expect(adminHtml).toContain('data-icon="logout"')
    expect(adminHtml).not.toContain('class="enlace-lateral__texto"')
    expect(estilosPortal).toContain('.portal--admin .boton--lateral::before { content: attr(data-icon); }')
    expect(estilosPortal).not.toContain('.portal--admin .barra-lateral nav a > span')
    expect(admin).toContain("cerrarAlertas.setAttribute('aria-label', 'Cerrar alertas operativas')")
  })
})
